name = "Spotify Playback Manager"
version = "1.0.0"
link = "https://github.com/jtljac"
source = "https://github.com/jtljac"
min-crankshaft-version = "0.2.2"

[author]
name = "jtljac"
link = "https://jacob-lucas.uk"

[entrypoints]

	[entrypoints.desktop]
	library = false
	menu = false

	[entrypoints.deck]
	library = false
	menu = false
	quick-access = true
